In [34]:
import requests
import pandas as pd

In [35]:
url = "https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100"

In [36]:
headers = {
    "Accept": "application/vnd.github+json",
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print("Status Code:", response.status_code)

Status Code: 200

In [37]:
data = response.json()

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['total_count', 'incomplete_results', 'items'])

In [38]:
df = pd.DataFrame(data["items"])

In [39]:
df.head()

,id,node_id,name,full_name,private,owner,html_url,description,fork,url,...,web_commit_signoff_required,has_pull_requests,pull_request_creation_policy,topics,visibility,forks,open_issues,watchers,default_branch,score
0,45717250,MDEwOlJlcG9zaXRvcnk0NTcxNzI1MA==,tensorflow,tensorflow/tensorflow,False,"{'login': 'tensorflow', 'id': 15658638, 'node_...",https://github.com/tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,False,https://api.github.com/repos/tensorflow/tensor...,...,False,True,all,"[deep-learning, deep-neural-networks, distribu...",public,76058,2865,197084,master,1.0
1,155220641,MDEwOlJlcG9zaXRvcnkxNTUyMjA2NDE=,transformers,huggingface/transformers,False,"{'login': 'huggingface', 'id': 25720743, 'node...",https://github.com/huggingface/transformers,🤗 Transformers: the model-definition framework...,False,https://api.github.com/repos/huggingface/trans...,...,False,True,all,"[audio, deep-learning, deepseek, gemma, glm, h...",public,34254,2382,164157,main,1.0
2,343965132,MDEwOlJlcG9zaXRvcnkzNDM5NjUxMzI=,ML-For-Beginners,microsoft/ML-For-Beginners,False,"{'login': 'microsoft', 'id': 6154722, 'node_id...",https://github.com/microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",False,https://api.github.com/repos/microsoft/ML-For-...,...,False,True,all,"[data-science, education, machine-learning, ma...",public,21954,11,89439,main,1.0
3,145553672,MDEwOlJlcG9zaXRvcnkxNDU1NTM2NzI=,funNLP,fighting41love/funNLP,False,"{'login': 'fighting41love', 'id': 11475294, 'n...",https://github.com/fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,False,https://api.github.com/repos/fighting41love/fu...,...,False,True,all,[],public,15267,53,82501,master,1.0
4,21872392,MDEwOlJlcG9zaXRvcnkyMTg3MjM5Mg==,awesome-machine-learning,josephmisiti/awesome-machine-learning,False,"{'login': 'josephmisiti', 'id': 246302, 'node_...",https://github.com/josephmisiti/awesome-machin...,A curated list of awesome Machine Learning fra...,False,https://api.github.com/repos/josephmisiti/awes...,...,False,True,all,[],public,15612,24,74035,master,1.0

In [40]:
df.shape

(100, 82)

In [41]:
df.columns

Index(['id', 'node_id', 'name', 'full_name', 'private', 'owner', 'html_url',
       'description', 'fork', 'url', 'forks_url', 'keys_url',
       'collaborators_url', 'teams_url', 'hooks_url', 'issue_events_url',
       'events_url', 'assignees_url', 'branches_url', 'tags_url', 'blobs_url',
       'git_tags_url', 'git_refs_url', 'trees_url', 'statuses_url',
       'languages_url', 'stargazers_url', 'contributors_url',
       'subscribers_url', 'subscription_url', 'commits_url', 'git_commits_url',
       'comments_url', 'issue_comment_url', 'contents_url', 'compare_url',
       'merges_url', 'archive_url', 'downloads_url', 'issues_url', 'pulls_url',
       'milestones_url', 'notifications_url', 'labels_url', 'releases_url',
       'deployments_url', 'created_at', 'updated_at', 'pushed_at', 'git_url',
       'ssh_url', 'clone_url', 'svn_url', 'homepage', 'size',
       'stargazers_count', 'watchers_count', 'language', 'has_issues',
       'has_projects', 'has_downloads', 'has_wiki', 'has_pages',
       'has_discussions', 'forks_count', 'mirror_url', 'archived', 'disabled',
       'open_issues_count', 'license', 'allow_forking', 'is_template',
       'web_commit_signoff_required', 'has_pull_requests',
       'pull_request_creation_policy', 'topics', 'visibility', 'forks',
       'open_issues', 'watchers', 'default_branch', 'score'],
      dtype='object')

In [42]:
df.dtypes

id                  int64
node_id            object
name               object
full_name          object
private              bool
                   ...
forks               int64
open_issues         int64
watchers            int64
default_branch     object
score             float64
Length: 82, dtype: object

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 82 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            100 non-null    int64
 1   node_id                       100 non-null    object
 2   name                          100 non-null    object
 3   full_name                     100 non-null    object
 4   private                       100 non-null    bool
 5   owner                         100 non-null    object
 6   html_url                      100 non-null    object
 7   description                   100 non-null    object
 8   fork                          100 non-null    bool
 9   url                           100 non-null    object
 10  forks_url                     100 non-null    object
 11  keys_url                      100 non-null    object
 12  collaborators_url             100 non-null    object
 13  teams_url                     100 non-null    object
 14  hooks_url                     100 non-null    object
 15  issue_events_url              100 non-null    object
 16  events_url                    100 non-null    object
 17  assignees_url                 100 non-null    object
 18  branches_url                  100 non-null    object
 19  tags_url                      100 non-null    object
 20  blobs_url                     100 non-null    object
 21  git_tags_url                  100 non-null    object
 22  git_refs_url                  100 non-null    object
 23  trees_url                     100 non-null    object
 24  statuses_url                  100 non-null    object
 25  languages_url                 100 non-null    object
 26  stargazers_url                100 non-null    object
 27  contributors_url              100 non-null    object
 28  subscribers_url               100 non-null    object
 29  subscription_url              100 non-null    object
 30  commits_url                   100 non-null    object
 31  git_commits_url               100 non-null    object
 32  comments_url                  100 non-null    object
 33  issue_comment_url             100 non-null    object
 34  contents_url                  100 non-null    object
 35  compare_url                   100 non-null    object
 36  merges_url                    100 non-null    object
 37  archive_url                   100 non-null    object
 38  downloads_url                 100 non-null    object
 39  issues_url                    100 non-null    object
 40  pulls_url                     100 non-null    object
 41  milestones_url                100 non-null    object
 42  notifications_url             100 non-null    object
 43  labels_url                    100 non-null    object
 44  releases_url                  100 non-null    object
 45  deployments_url               100 non-null    object
 46  created_at                    100 non-null    object
 47  updated_at                    100 non-null    object
 48  pushed_at                     100 non-null    object
 49  git_url                       100 non-null    object
 50  ssh_url                       100 non-null    object
 51  clone_url                     100 non-null    object
 52  svn_url                       100 non-null    object
 53  homepage                      92 non-null     object
 54  size                          100 non-null    int64
 55  stargazers_count              100 non-null    int64
 56  watchers_count                100 non-null    int64
 57  language                      77 non-null     object
 58  has_issues                    100 non-null    bool
 59  has_projects                  100 non-null    bool
 60  has_downloads                 100 non-null    bool
 61  has_wiki                      100 non-null    bool
 62  has_pages                     100 non-null    bool
 63  has_discussions               100 non-null    bool
 64  forks_count                   100 non-null    int64
 65  mirror_url                    0 non-null      object
 66  archived                      100 non-null    bool
 67  disabled                      100 non-null    bool
 68  open_issues_count             100 non-null    int64
 69  license                       78 non-null     object
 70  allow_forking                 100 non-null    bool
 71  is_template                   100 non-null    bool
 72  web_commit_signoff_required   100 non-null    bool
 73  has_pull_requests             100 non-null    bool
 74  pull_request_creation_policy  100 non-null    object
 75  topics                        100 non-null    object
 76  visibility                    100 non-null    object
 77  forks                         100 non-null    int64
 78  open_issues                   100 non-null    int64
 79  watchers                      100 non-null    int64
 80  default_branch                100 non-null    object
 81  score                         100 non-null    float64
dtypes: bool(14), float64(1), int64(9), object(58)
memory usage: 54.6+ KB

In [44]:
df = df[
    [
        "name",
        "owner",
        "language",
        "stargazers_count",
        "forks_count",
        "watchers_count",
        "open_issues_count",
        "created_at",
        "updated_at",
        "license"
    ]
]

In [45]:
df.columns

Index(['name', 'owner', 'language', 'stargazers_count', 'forks_count',
       'watchers_count', 'open_issues_count', 'created_at', 'updated_at',
       'license'],
      dtype='object')

In [46]:
df["owner"] = df["owner"].apply(
    lambda x: x["login"] if isinstance(x, dict) else None
)

In [47]:
df["license"] = df["license"].apply(
    lambda x: x["name"] if isinstance(x, dict) else None
)

In [48]:
df.head()

,name,owner,language,stargazers_count,forks_count,watchers_count,open_issues_count,created_at,updated_at,license
0,tensorflow,tensorflow,C++,197084,76058,197084,2865,2015-11-07T01:19:20Z,2026-08-16T18:21:21Z,Apache License 2.0
1,transformers,huggingface,Python,164157,34254,164157,2382,2018-10-29T13:56:00Z,2026-08-16T18:27:42Z,Apache License 2.0
2,ML-For-Beginners,microsoft,Jupyter Notebook,89439,21954,89439,11,2021-03-03T01:34:05Z,2026-08-16T18:28:30Z,MIT License
3,funNLP,fighting41love,Python,82501,15267,82501,53,2018-08-21T11:20:39Z,2026-08-16T17:29:18Z,None
4,awesome-machine-learning,josephmisiti,Python,74035,15612,74035,24,2014-07-15T19:11:19Z,2026-08-16T17:16:22Z,Other

In [49]:
df.isnull().sum()

name                  0
owner                 0
language             23
stargazers_count      0
forks_count           0
watchers_count        0
open_issues_count     0
created_at            0
updated_at            0
license              22
dtype: int64

In [50]:
df["language"] = df["language"].fillna("Unknown")

In [51]:
df["license"] = df["license"].fillna("No License")

In [52]:
df.isnull().sum()

name                 0
owner                0
language             0
stargazers_count     0
forks_count          0
watchers_count       0
open_issues_count    0
created_at           0
updated_at           0
license              0
dtype: int64

In [53]:
df.duplicated(subset=["name", "owner"]).sum()

np.int64(0)

In [54]:
df = df.drop_duplicates(subset=["name", "owner"])

In [55]:
df["created_at"] = pd.to_datetime(df["created_at"])
df["updated_at"] = pd.to_datetime(df["updated_at"])

In [56]:
df = df.rename(columns={
    "stargazers_count": "stars",
    "forks_count": "forks",
    "watchers_count": "watchers",
    "open_issues_count": "open_issues",
    "created_at": "created_date",
    "updated_at": "updated_date"
})

In [57]:
df.columns

Index(['name', 'owner', 'language', 'stars', 'forks', 'watchers',
       'open_issues', 'created_date', 'updated_date', 'license'],
      dtype='object')

In [58]:
df.head()

,name,owner,language,stars,forks,watchers,open_issues,created_date,updated_date,license
0,tensorflow,tensorflow,C++,197084,76058,197084,2865,2015-11-07 01:19:20+00:00,2026-08-16 18:21:21+00:00,Apache License 2.0
1,transformers,huggingface,Python,164157,34254,164157,2382,2018-10-29 13:56:00+00:00,2026-08-16 18:27:42+00:00,Apache License 2.0
2,ML-For-Beginners,microsoft,Jupyter Notebook,89439,21954,89439,11,2021-03-03 01:34:05+00:00,2026-08-16 18:28:30+00:00,MIT License
3,funNLP,fighting41love,Python,82501,15267,82501,53,2018-08-21 11:20:39+00:00,2026-08-16 17:29:18+00:00,No License
4,awesome-machine-learning,josephmisiti,Python,74035,15612,74035,24,2014-07-15 19:11:19+00:00,2026-08-16 17:16:22+00:00,Other

In [59]:
df.shape

(100, 10)

In [60]:
df.to_csv("github_projects.csv", index=False)

In [61]:
import os

os.path.exists("github_projects.csv")

True

In [62]:
df_check = pd.read_csv("github_projects.csv")

In [63]:
df_check.head()

,name,owner,language,stars,forks,watchers,open_issues,created_date,updated_date,license
0,tensorflow,tensorflow,C++,197084,76058,197084,2865,2015-11-07 01:19:20+00:00,2026-08-16 18:21:21+00:00,Apache License 2.0
1,transformers,huggingface,Python,164157,34254,164157,2382,2018-10-29 13:56:00+00:00,2026-08-16 18:27:42+00:00,Apache License 2.0
2,ML-For-Beginners,microsoft,Jupyter Notebook,89439,21954,89439,11,2021-03-03 01:34:05+00:00,2026-08-16 18:28:30+00:00,MIT License
3,funNLP,fighting41love,Python,82501,15267,82501,53,2018-08-21 11:20:39+00:00,2026-08-16 17:29:18+00:00,No License
4,awesome-machine-learning,josephmisiti,Python,74035,15612,74035,24,2014-07-15 19:11:19+00:00,2026-08-16 17:16:22+00:00,Other

In [64]:
df_check.shape

(100, 10)

In [65]:
df_check.columns

Index(['name', 'owner', 'language', 'stars', 'forks', 'watchers',
       'open_issues', 'created_date', 'updated_date', 'license'],
      dtype='object')